#!/bin/bash

set -e

if [ -d "$HOME/git/arduino/hardware/keyboardio" ]; then
	cd $HOME/git/arduino/hardware/keyboardio/avr
	make update-submodules
else
	mkdir -p "$HOME/git/arduino/hardware/keyboardio"
	git clone --recursive git@github.com:keyboardio/Arduino-Boards.git "$HOME/git/arduino/hardware/keyboardio/avr"
fi
